[package]
name = "heatup"
version = "0.1.0"
edition = "2021"

[dependencies]
good_lp = { version = "1", features = ["highs"], default-features = false }
lazy_static = "1.4.0"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"
